test(megolm): Add mutation tests
matrix-org/vodozemac pull request #142
Opened 2024-04-09 08:56 UTC by Johennes

This fixes the following issues:

```
MISSED   src/megolm/group_session.rs:80:9: replace GroupSession::session_config -> SessionConfig with Default::default() in 0.8s build + 3.1s test
MISSED   src/megolm/inbound_group_session.rs:289:47: replace < with == in InboundGroupSession::find_ratchet in 0.8s build + 3.1s test
MISSED   src/megolm/inbound_group_session.rs:302:9: replace InboundGroupSession::verify_mac -> Result<(), DecryptionError> with Ok(()) in 1.0s build + 3.1s test
MISSED   src/megolm/message.rs:133:9: replace MegolmMessage::add_signature -> Result<(), SignatureError> with Ok(()) in 0.8s build + 3.7s test
MISSED   src/megolm/message.rs:282:42: replace + with - in <impl TryFrom for MegolmMessage>::try_from in 0.8s build + 3.0s test
MISSED   src/megolm/message.rs:50:54: replace + with * in 0.8s build + 3.2s test
MISSED   src/megolm/message.rs:54:9: replace MegolmMessage::ciphertext -> &[u8] with Vec::leak(Vec::new()) in 0.8s build + 3.0s test
MISSED   src/megolm/message.rs:54:9: replace MegolmMessage::ciphertext -> &[u8] with Vec::leak(vec![0]) in 0.8s build + 3.4s test
MISSED   src/megolm/message.rs:54:9: replace MegolmMessage::ciphertext -> &[u8] with Vec::leak(vec![1]) in 0.8s build + 3.0s test
MISSED   src/megolm/message.rs:59:9: replace MegolmMessage::message_index -> u32 with 0 in 0.8s build + 2.9s test
MISSED   src/megolm/message.rs:59:9: replace MegolmMessage::message_index -> u32 with 1 in 0.8s build + 3.0s test
MISSED   src/megolm/message.rs:64:9: replace MegolmMessage::mac -> &[u8] with Vec::leak(Vec::new()) in 0.8s build + 3.1s test
MISSED   src/megolm/message.rs:64:9: replace MegolmMessage::mac -> &[u8] with Vec::leak(vec![0]) in 0.8s build + 3.2s test
MISSED   src/megolm/message.rs:64:9: replace MegolmMessage::mac -> &[u8] with Vec::leak(vec![1]) in 0.9s build + 3.3s test
MISSED   src/megolm/mod.rs:34:5: replace default_config -> SessionConfig with Default::default() in 0.8s build + 3.2s test
MISSED   src/megolm/ratchet.rs:218:31: replace < with == in Ratchet::advance_to in 0.7s build + 3.0s test
MISSED   src/megolm/session_config.rs:33:9: replace SessionConfig::version -> u8 with 0 in 0.8s build + 3.0s test
MISSED   src/megolm/session_config.rs:33:9: replace SessionConfig::version -> u8 with 1 in 0.8s build + 3.5s test
MISSED   src/megolm/session_keys.rs:141:9: replace <impl Zeroize for ExportedSessionKey>::zeroize with () in 1.0s build + 3.2s test
MISSED   src/megolm/session_keys.rs:291:9: replace <impl Zeroize for SessionKey>::zeroize with () in 0.9s build + 3.2s test
TIMEOUT  src/megolm/ratchet.rs:230:23: replace -= with += in Ratchet::advance_to in 0.8s build + 23.0s test
TIMEOUT  src/megolm/ratchet.rs:230:23: replace -= with /= in Ratchet::advance_to in 0.8s build + 23.0s test
```

Relates to: #78

2024-04-09 09:07 UTC, Johennes commented
Looks like the clippy errors are due to a new rule on nightly.

2024-04-29 07:51 UTC, poljar requested changes
Looks good, though there's a stray `println` left over.

2024-04-29 07:51 UTC, poljar commented on src/megolm/message.rs
> +        println!("{:?}", signature.to_bytes());
Leftover `println()`.

2024-04-29 07:55 UTC, Johennes commented on src/megolm/message.rs
> +        println!("{:?}", signature.to_bytes());
Argh, sorry. 🤦‍♂️

2024-04-29 08:01 UTC, Johennes commented
Hm, looks like the CI ran on an ARM Mac

>   Image: macos-14-arm64

but then installed the x86 rust toolchain

> Run rustup toolchain install stable-x86_64-apple-darwin --profile minimal --no-self-update

which then results in

> /Users/runner/work/_temp/39f7e4d6-3a3c-42b0-9e65-200e32c1e151.sh: line 1: cargo: command not found

🤔

2024-04-29 08:17 UTC, Johennes commented
So according to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-private-repositories `macos-latest` currently aliases `macos-14` and always runs on M1. I'm not sure what suddenly changed here because last week it still resolved to `macos-12` as evidenced by https://github.com/matrix-org/vodozemac/actions/runs/8779442225/job/24087554656#step:1:8.

@poljar do you want CI for macOS to run on both x86 and ARM Mac or would just ARM be enough?

2024-04-29 12:07 UTC, Johennes commented
> Hmm, obviously both are better, but I'm happy to have any CI for Mac. So ARM only would be enough.

Since the CI job was already set up via a matrix strategy, it was actually pretty easy to just build on both. I hope it's ok that I added the small change in this PR directly.

2024-04-29 12:18 UTC, poljar commented
> > Hmm, obviously both are better, but I'm happy to have any CI for Mac. So ARM only would be enough.
> 
> Since the CI job was already set up via a matrix strategy, it was actually pretty easy to just build on both. I hope it's ok that I added the small change in this PR directly.

Yeah that's fine.

2024-04-29 15:49 UTC, poljar commented
> I don't know why codecov is hanging now. I already tried it three or four times by now. 🤷‍♂️

Hmm, no idea either. Maybe it'll untangle itself once merged.

2024-04-29 15:50 UTC, poljar approved these changes

2024-04-29 15:51 UTC, merged