Add support to encrypt messages without MAC truncation
matrix-org/vodozemac pull request #74
Opened 2022-07-05 11:39 UTC by poljar

2022-08-04 14:08 UTC, dkasak requested changes

2022-08-04 14:08 UTC, dkasak commented on src/megolm/session_config.rs
> +    /// individual messages. The MAC will be truncated to 8 bytes.
```suggestion
    /// Create a `SessionConfig` for the Megolm version 1. This version of
    /// Megolm uses AES-256 and HMAC with a truncated MAC to encrypt individual
    /// messages. The MAC will be truncated to 8 bytes.
```

2022-08-04 14:08 UTC, dkasak commented on src/megolm/session_config.rs
> +    /// MAC won't be truncated.
```suggestion
    /// Create a `SessionConfig` for the Megolm version 2. This version of
    /// Megolm uses AES-256 and HMAC to encrypt individual messages. The MAC
    /// won't be truncated.
```

2022-08-04 14:08 UTC, dkasak commented on src/olm/messages/message.rs
>                  Err(DecodeError::InvalidMacLength(Mac::TRUNCATED_LEN, mac_slice.len()))
```suggestion
                Err(DecodeError::InvalidMacLength(mac_length, mac_slice.len()))
```

2022-08-04 16:16 UTC, poljar commented on src/megolm/group_session.rs
> +            Version::V2 => MegolmMessage::encrypt_private(
https://github.com/matrix-org/vodozemac/pull/74/commits/002b7abb6f4c2c0031455836ff1ede6f66d2b281

2022-08-05 09:24 UTC, dkasak approved these changes

2022-08-05 10:17 UTC, merged